PROJECT_DIR="/mnt/d/LLM-Project/FinalRAG-Retrieval/EIC-RAG-Project"

LANCEDB_DIR="/mnt/d/LLM-Project/my-app/lancedb_meta_data"

OPENAI_API_KEY="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"

TRUBRICS_EMAIL="ai4eic@gmail.com"
TRUBRICS_PASSWORD="William&Mary"
