PROJECT_DIR="/mnt/d/LLM-Project/FinalRAG-Retrieval/EIC-RAG-Project"

USER_DB="/mnt/d/LLM-Project/FinalRAG-Retrieval/EIC-RAG-Project/streamlit_app/users.sqlite"

LANCEDB_DIR="/mnt/d/LLM-Project/my-app/lancedb_meta_data"

CHROMADB_DIR="/mnt/d/LLM-Project/FinalRAG-Retrieval/EIC-RAG-Project/ingestion/EIC_PyPDF"

OPENAI_API_KEY="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"

LANGCHAIN_TRACING_V2="true"
LANGCHAIN_API_KEY="ls__0e971467c927446e9d8ea2bd1a4b793a"
LANGCHAIN_ENDPOINT="https://api.smith.langchain.com"
LANGCHAIN_PROJECT="Test-LLM4EIC-RAG"
LANGCHAIN_EVAL_PROJECT="TEST-LLM4EIC-RAG-EVAL"

TRUBRICS_EMAIL="ai4eic@gmail.com"
TRUBRICS_PASSWORD="William&Mary"
